version: 0.2

phases:
  install:
    commands:
      - echo "Setting environment"
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"
      - cd "$CODEBUILD_SRC_DIR"
      - source deployment-scripts/env.sh
  build:
    commands:
      - echo "Deploying Terraform..."
      - S3_TERRAFORM_STATE_BUCKET=${TF_VAR_STATE_BUCKET} S3_TERRAFORM_STATE_REGION=${S3_TERRAFORM_STATE_REGION} bash deployment-scripts/create-bucket.sh
      - echo ${S3_TERRAFORM_STATE_BUCKET}
      - terraform init -backend-config="bucket=${TF_VAR_STATE_BUCKET}" -backend-config="key=${S3_TERRAFORM_STATE_KEY}" -backend-config="region=${S3_TERRAFORM_STATE_REGION}"
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "Uploading Source Code"
      - (cd code && tar -czvf sourcedir.tar.gz workflow/.)
      - aws s3 cp "code/workflow/" "s3://${SOURCE_BUCKET}/code/" --recursive
      - aws s3 cp code/sourcedir.tar.gz "s3://${SOURCE_BUCKET}/code/"
      - aws s3 cp "config/manifest.json" "s3://${SOURCE_BUCKET}/config/manifest.json"

artifacts:
  files:
    - '**/*'
