Parameters:
  GithubOrg: # can also be a regular user
    Type: String
    Default:
  FullRepoName:
    Type: String
    Default:

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GithubActionsDeployInfra
      ManagedPolicyArns: [arn:aws:iam::aws:policy/AdministratorAccess]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${FullRepoName}:*
   GithubOidc:
     Type: AWS::IAM::OIDCProvider
     Properties:
       Url: https://token.actions.githubusercontent.com
       ThumbprintList: [6938fd4d98bab03faadb97b34396831e3780aea1]
       ClientIdList:
         - !Sub https://github.com/${GithubOrg}
         - sts.amazonaws.com

Outputs:
  Role:
    Value: !GetAtt Role.Arn     
